name: Guardian Terraform Plan

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - 'src/**'

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Guardian Plan Execution
        uses: abcxyz/guardian/actions/terraform-plan@v0.1.0
        with:
          directory: terraform
